sudo: required
services:
  - docker

before_install:
  - docker build -t karthikr7/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true karthikr7/docker-react-udemy npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react-udemy"
    env: "Docker-react-udemy-env"
    bucket_name: "elasticbeanstalk-us-east-1-827130695306"
    bucket_path: "docker-react-udemy"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY